
export const SET_INPUT_AUTH = 'SET_INPUT_AUTH'
export const SET_INPUT_CONTACT = 'SET_INPUT_CONTACT'

export const ADD_CONTACT = 'ADD_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const REDACT_CONTACT = 'REDACT_CONTACT'

export const SORT_CONTACT_A_TO_Z = 'SORT_CONTACT_A_TO_Z'
export const SORT_CONTACT_Z_TO_A = 'SORT_CONTACT_Z_TO_A'
export const FILTER_CONTACT = 'FILTER_CONTACT'