export const SET_FIRST_NAME = 'SET_FIRST_NAME'
export const SET_TELEPHONE = 'SET_TELEPHONE'

export const ADD_CONTACT = 'ADD_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const REDACT_CONTACT = 'REDACT_CONTACT'
export const SET_NEW_CONTACT_FIRST_NAME = 'SET_NEW_CONTACT_FIRST_NAME'
export const SET_NEW_CONTACT_TELEPHONE = 'SET_NEW_CONTACT_TELEPHONE'